src/Entity/Spaceship.php
<?php

namespace App\Entity;

use App\Repository\SpaceshipRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SpaceshipRepository::class)
 */
class Spaceship
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $franchise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $purpose;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $size;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $size_crew;

    /**
     * @ORM\Column(type="bigint")
     */
    private $price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $available = 0;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $height;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $length;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $width;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $assets;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_path;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFranchise(): ?string
    {
        return $this->franchise;
    }

    public function setFranchise(?string $franchise): self
    {
        $this->franchise = $franchise;

        return $this;
    }

    public function getPurpose(): ?string
    {
        return $this->purpose;
    }

    public function setPurpose(string $purpose): self
    {
        $this->purpose = $purpose;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getSizeCrew(): ?int
    {
        return $this->size_crew;
    }

    public function setSizeCrew(?int $size_crew): self
    {
        $this->size_crew = $size_crew;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAvailable(): ?int
    {
        return $this->available;
    }

    public function setAvailable(int $available): self
    {
        $this->available = $available;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(?int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getLength(): ?int
    {
        return $this->length;
    }

    public function setLength(?int $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(?int $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getAssets(): ?string
    {
        return $this->assets;
    }

    public function setAssets(?string $assets): self
    {
        $this->assets = $assets;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(?string $image_path): self
    {
        $this->image_path = $image_path;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Build your Fleet {% endblock %}</title>
        {% block stylesheets %}
            <link rel="icon" type="image/png" href="{{ asset('/img/Icon.png') }}"/>
            <link rel="stylesheet" href="/css/app.css">
        {% endblock %}
    </head>
    
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/homepage.html.twig
{% extends 'base.html.twig' %}


{% block title %} {{ parent() }} - Homepage {% endblock %}


{% block body %}
    <!-- BACKGROUND OF THE PAGE -->
    <style>
        body, html
        {
            background-image: url("img/Wallpaper_Homepage.jpg"); 
        }
    </style>

    {% include 'components/button_connection.html.twig' %}
    {% include 'components/button_title.html.twig' %}
{% endblock %}

templates/mainpage.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <!-- BACKGROUND OF THE PAGE -->
    <style>
        body, html
        {
            background-image: url("img/Wallpaper_Mainpage.jpg"); 
        }
    </style>

    <!-- Buttons at the top of the page -->
    {% include 'components/button_sorting.html.twig' %}
    {% include 'components/button_connection.html.twig' %}
    {% include 'components/button_title.html.twig' %}

    <!-- We display all our Spaceships -->
    {% for spaceship in spaceships %}
        
        <div class="custom-box">
            <a href="{{ path('spaceship_show', {'id' : spaceship.id }) }}">

                <div style="font-size: 64px">
                    {{ spaceship.name }}
                </div>

                <div style="font-size: 48px">	
                    ~ {{ spaceship.franchise }} ~
                </div>
                <div class="flex-container" style="margin:30px;">
                    <table align=center>
                        <tr>
                            <img src="{{ spaceship.getImagePath }}" alt="picture of {{ spaceship.name }}">
                        </tr>

                        <tr>
                            <div>
                                <table align=center>
                                    <tr>
                                        <th>Size</th>
                                        <th>{{ spaceship.size }}</th>
                                    </tr>

                                    <tr>
                                        <td>Purpose</td>
                                        <td>{{ spaceship.purpose }}</td>
                                    </tr>

                                    <tr>
                                        <td>Crew Size</td>
                                        <td>
                                            {% if spaceship.sizeCrew is null %}
                                                Unknown
                                            {% else %}
                                                {{ spaceship.sizeCrew|number_format(0, '.', ' ') }}
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Price</td>
                                        <td>
                                            {% if spaceship.price is null %}
                                                Unknown
                                            {% else %}
                                                {{ spaceship.price|number_format(2, '.', ' ') }}
                                            {% endif %}
                                        </td>
                                    </tr>				  

                                    <tr>
                                        <td>Assets</td>
                                        <td>
                                            {% if spaceship.assets is null %}
                                                Unknown
                                            {% else %}
                                                {{ spaceship.assets }}
                                            {% endif %}
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </tr>
                    </table>
                </div>
            </a>
        </div>

    {% else %}
    
        <!-- else : there was 0 spaceship, so we display an error message instead -->
        <div class="custom-box-small" style="font-size: 48px">
            Sorry, There is no Spaceship to display here...
            <br>
            <br>
            Sorry for the inconvenience:'(
        </div>

    {% endfor %}

    <!-- A button to go back to the top of the page -->
    {% include 'components/button_mainpage.html.twig' %}

{% endblock %}